### ISSUE TITLE
inline 的写法在local访问时有问题

### ISSUE THREAD

**Issue by helinjiang** [feflow/builder-webpack3#10]
通过代理的方式没有问题，但是如果直接访问 localhost，则会发现 inline 失败
![image](https://user-images.githubusercontent.com/13464168/37189903-b272942a-2391-11e8-862a-b4e6c77d9073.png)

**Comment by cpselvis** [comment]
这个是因为新项目使用了antd, antd里面有import '.css' 语法。builder-webpack3之前不支持.css，只支持.scss。现在已经支持了.css文件。在v0.2.14版本中可以使用。修复提交参考：https://github.com/feflow/builder-webpack3/commit/5878cdd6f35b8d5d3249bf71b3a47a7403fa88e3
