### ISSUE TITLE
对项目名的分解有问题

### ISSUE THREAD

**Issue by helinjiang** [feflow/builder-webpack3#19]
项目名为 `now-activity-awake-spring` ，被解析之后的 `bizName` 为 `awake`，但预期值为 `awake-spring`

**Comment by cpselvis** [comment]
在  `@tencent/generator-now-webpack`  里的 v0.1.7版本的时候已经修复此问题。之前是因为正则表达写的有问题，原正则表达式：
```
/^(now|shangfen)-([a-zA-Z0-9]*)-([a-zA-Z0-9]*)/)
```
修复后的：
```
/^(now|shangfen)-([a-zA-Z0-9]*)-(.*)/)
```

本地 feflow init的时候会提升增量更新脚手架。
