### ISSUE TITLE
不要限制一定要 init.js

### ISSUE THREAD

**Issue by helinjiang** [feflow/builder-webpack3#23]
部分页面中因为太简单了，几乎不需要写js，比如规则，全是 html，但是限于当前的版本，必须得加一个空的 init.js 文件。加也就加了吧，最后会生成一个不到 1K 的文件，居然也不自动 inline 到 html 中！

**Comment by cpselvis** [comment]
已经支持，在v0.3.8版本可以使用这个feature。提交的commit: https://github.com/feflow/builder-webpack3/commit/3d005969acfad4f8158367ddf4d5f90e3d6ff9ed
