### ISSUE TITLE
feflow dev 等命令时，不要自动更新 generator

### ISSUE THREAD

**Issue by helinjiang** [feflow/builder-webpack3#29]
目前无论执行任何命令，都会自动去更新 generator，如果本地安装的 generator 比较多，更新又频繁的话，每次启动项目都要等更新完。我的windows下等这个操作基本要等2分钟以上才能够完成，很影响效率啊

建议：generator 只是项目脚手架，在运行 `feflow init ` 等相关命令的时候才去检查更新，类似 `fefllow dev` 等命令与项目脚手架有毛关系，有必要去检查吗？

**Comment by cpselvis** [comment]
已经支持。feflow-cli 的 v0.13.3 版本集成此功能。
