### ISSUE TITLE
11.url.cn 中的公共包地址非压缩版本是有问题的

### ISSUE THREAD

**Issue by helinjiang** [feflow/builder-webpack3#34]
如下，正常情况下是引入压缩版本

![image](https://user-images.githubusercontent.com/13464168/42748885-4b8f445e-8914-11e8-8eda-ad4ef82e93b3.png)

但是在开发场景下有时需要引入 dev 版本的 react。但是 http://11.url.cn/now/lib/16.2.0/react.js 这个地址的包是有问题的，因为如下代码是非法的：

![image](https://user-images.githubusercontent.com/13464168/42748970-a7780634-8914-11e8-8669-0c79fc702c42.png)

请修复之，或者提供一个合法的 umd 链接地址。同理， react-dom 也请一并提供

**Comment by cpselvis** [comment]
已经解决了：http://11.url.cn/now/lib/16.2.0/react.js
http://11.url.cn/now/lib/16.2.0/react-dom.js

改成了 umd 的包
