### ISSUE TITLE
本地构建的开发版本的css跟build出来发布版本css不一致

### ISSUE THREAD

**Issue by orangekurt** [feflow/builder-webpack3#35]
本地构建的开发版本的css跟build出来发布版本css不一致

**Comment by LeoEatle** [comment]
这里的不一致是指内容不一致？
可能具体要看`devConfig`和`prodConfig`的不同
这个issue最好移至builder-webpack-core

**Comment by cpselvis** [comment]
这个地方应该是和具体的机器有关系，本地执行 feflow build时你的系统是windows环境，而线上的发布机器环境是linux
